image: robertcnelson/beagle-devscripts-debian-12-arm64:latest
# https://openbeagle.org/beagleboard/ci-docker-images

stages:
  - lint
  - deploy

lint:
  stage: lint
  before_script:
    - apt-get update && apt-get install -y jsonlint
  script:
    - jsonlint -v os_list.json

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - eval "$(ssh-agent -s)"
    - echo "${PRIVATE_KEY}" | base64 -d | ssh-add -
    - rsync -e 'scp -p 45 -o "StrictHostKeyChecking=no"' -vP os_list.json docs@beagleboard.org:/mnt/debian/distros.json
  only:
    - main
